---
title: "Hello"
author: "IsaevaA.S."
output: html_document
---

```{r setup, include=FALSE}

library(readr)
library(dplyr)
library(tidyr)
library(lubridate)
library (vegan)
source("data.R")

knitr::opts_chunk$set(echo = TRUE)
```


```{r}
top10<-read.csv("billboard.csv") |>
  select (date = "Date",
          song= "Song",
          artist="Artist")

```

```{r}
modern<-top10 |>
  filter( date >= "1980-01-01")


```

```{r}
artists<-modern|>
  count(artist) |>
  arrange(-n) |>
  filter(!artist %in% c("Soundtrack", "Various Artists"))
head(artists)
```


```{r}
set.seed(2)
xs<- sample(1:100, 25)
xs
```

```{r}
me <-median(xs)
```

Median is `r me`

```{r}
artists[xs,] |>
  arrange(-n) |>
  gt::gt()
```


```{r}
top10diversity <- top10 %>%
  mutate (date = as.Date(date)) %>% 
  mutate(date = year(as.Date(date))) 
```

```{r}
frequency_matrix <- top10diversity %>%
  group_by(date, artist) %>%
  summarise(Count = n(), .groups = "drop") %>%
  pivot_wider(names_from = artist, values_from = Count, values_fill = 0)
```

```{r}
frequency_matrix <- as.data.frame(frequency_matrix)
rownames(frequency_matrix) <- frequency_matrix$date
frequency_matrix <- frequency_matrix[, -1]
```

